{
    "cveId": "CVE-2024-38875",
    "version": "1.0.0",
    "timestamp": "2024-12-06T11:32:07.789868+00:00",
    "description": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
    "keyphrases": {
        "rootcause": "",
        "weakness": "",
        "impact": "denial of service",
        "vector": "certain inputs with a very large number of brackets",
        "attacker": "",
        "product": "Django",
        "version": "4.2 before 4.2.14 and 5.0 before 5.0.7",
        "component": "urlize and urlizetrunc"
    }
}
