{
    "cveId": "CVE-2010-3493",
    "version": "1.0.0",
    "timestamp": "2024-12-10T17:54:04.992951+00:00",
    "description": "Multiple race conditions in smtpd.py in the smtpd module in Python 2.6, 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, or the getpeername function having an ENOTCONN error, a related issue to CVE-2010-3492.",
    "keyphrases": {
        "rootcause": "multiple race conditions",
        "weakness": "",
        "impact": [
            "daemon outage",
            "unexpected return value of None",
            "ECONNABORTED",
            "EAGAIN",
            "EWOULDBLOCK error",
            "ENOTCONN error"
        ],
        "vector": "establishing and immediately closing a TCP connection",
        "attacker": "remote attackers",
        "product": "Python",
        "version": [
            "2.6",
            "2.7",
            "3.1",
            "3.2 alpha"
        ],
        "component": "smtpd module"
    }
}
