{
    "cveId": "CVE-2010-3494",
    "version": "1.0.0",
    "timestamp": "2024-12-10T17:54:04.992951+00:00",
    "description": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492.",
    "keyphrases": {
        "rootcause": "race condition",
        "weakness": "",
        "impact": "denial of service",
        "vector": "establishing and then immediately closing a TCP connection",
        "attacker": "remote attackers",
        "product": "pyftpdlib",
        "version": "before 0.5.2",
        "component": "FTPHandler class in ftpserver.py"
    }
}
