{
    "cveId": "CVE-2010-3495",
    "version": "1.0.0",
    "timestamp": "2024-12-10T17:54:04.992951+00:00",
    "description": "Race condition in ZEO/StorageServer.py in Zope Object Database (ZODB) before 3.10.0 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492.",
    "keyphrases": {
        "rootcause": "race condition",
        "weakness": "",
        "impact": "denial of service (daemon outage)",
        "vector": "establishing and then immediately closing a TCP connection",
        "attacker": "remote attackers",
        "product": "Zope Object Database",
        "version": "before 3.10.0",
        "component": "ZEO/StorageServer.py"
    }
}
